### ISSUE TITLE
[Core][flytekit] TypeTransformer support for Pydantic Models 

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#1823] opened 2021-11-11 22:48 UTC
### Motivation: Why do you think this is important?

Currently Flytekit supports dataclasses as supported user defined types. We should also support Pydantic, as it provides similar benefits as Dataclasses_json to extract the schema and serialize to JSON with a nice extensible format.

### Goal: What should the final outcome look like, ideally?

```python
from typing import List
from pydantic import BaseModel


class Foo(BaseModel):
    count: int
    size: float = None
```

Support as a valid transform

### Describe alternatives you've considered 

dataclasses are already supported, but they allow limited extensibility to schema extraction as they use marshmallow underneath

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by cosmicBboy** [comment] 2023-02-27 22:09
duplicate of https://github.com/flyteorg/flyte/issues/2686

**Closed by cosmicBboy** 2023-02-27 22:09 UTC
Labels: enhancement, flytekit
