### ISSUE TITLE
[BUG] Timeline View breaks page on nested workflows

### ISSUE THREAD

**Issue by jsonporter** [flyteorg/flyte#2274] opened 2022-03-17 16:55 UTC
### Describe the bug

When viewing some executions in timeline view, there is a bug where clicking on certain nested parents causes the browser to freeze and crash. This bug is somewhat transient (doesn't occur in all cases) however the one workflow that can reliably repo the bug is: `console/projects/cluster-deploy/domains/development/executions/fca7d008dc9ab42f2856?duration=all`

Steps to repo:
1. Click link, go to timeline view
2. Click on `provision_sub_account`

### Expected behavior

The nested parent should open displaying its children. 

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by anrusina** [comment] 2022-03-17 17:01
Duplicate of https://github.com/flyteorg/flyteconsole/issues/332.

**Comment by anrusina** [comment] 2022-03-21 19:06
Closed as a duplicate

**Closed by anrusina** 2022-03-21 19:06 UTC
Labels: bug, ui, untriaged
