### ISSUE TITLE
[FlyteCTL Feature] `get task --version` filters all tasks by version

### ISSUE THREAD

**Issue by tekumara** [flyteorg/flyte#3679] opened 2023-05-14 01:17 UTC
### Describe the feature/command for FlyteCTL

Current behaviour:
```
❯ flytectl get task -p flytesnacks -d development --version v3
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| VERSION (15)  | NAME                                     | TYPE        | INPUTS             | OUTPUTS  | DISCOVERABLE | DISCOVERY VERSION | CREATED AT                  |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v3            | aircraft.etl_flow.load_live_data         | python-task | live_aircraft_data |          |              |                   | 2023-05-13T13:03:28.197109Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v3            | aircraft.etl_flow.load_reference_data    | python-task | airlines           |          |              |                   | 2023-05-13T13:03:28.189977Z |
|               |                                          |             | airports           |          |              |                   |                             |
|               |                                          |             | routes             |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v3            | aircraft.etl_flow.transform              | python-task | airlines           | o0       |              |                   | 2023-05-13T13:03:28.182702Z |
|               |                                          |             | raw_aircraft_data  |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v3            | aircraft.etl_flow.extract_live_data      | python-task |                    | o0       |              |                   | 2023-05-13T13:03:28.173540Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v3            | aircraft.etl_flow.extract_reference_data | python-task |                    | airlines |              |                   | 2023-05-13T13:03:28.159936Z |
|               |                                          |             |                    | airports |              |                   |                             |
|               |                                          |             |                    | routes   |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v2            | aircraft.etl_flow.load_live_data         | python-task | live_aircraft_data |          |              |                   | 2023-05-13T12:39:17.548179Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v2            | aircraft.etl_flow.load_reference_data    | python-task | airlines           |          |              |                   | 2023-05-13T12:39:17.540335Z |
|               |                                          |             | airports           |          |              |                   |                             |
|               |                                          |             | routes             |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v2            | aircraft.etl_flow.transform              | python-task | airlines           | o0       |              |                   | 2023-05-13T12:39:17.531564Z |
|               |                                          |             | raw_aircraft_data  |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v2            | aircraft.etl_flow.extract_live_data      | python-task |                    | o0       |              |                   | 2023-05-13T12:39:17.523488Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v2            | aircraft.etl_flow.extract_reference_data | python-task |                    | airlines |              |                   | 2023-05-13T12:39:17.508720Z |
|               |                                          |             |                    | airports |              |                   |                             |
|               |                                          |             |                    | routes   |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v1            | aircraft.etl_flow.load_live_data         | python-task | live_aircraft_data |          |              |                   | 2023-05-13T05:24:48.797097Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v1            | aircraft.etl_flow.load_reference_data    | python-task | airlines           |          |              |                   | 2023-05-13T05:24:48.787874Z |
|               |                                          |             | airports           |          |              |                   |                             |
|               |                                          |             | routes             |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v1            | aircraft.etl_flow.transform              | python-task | airlines           | o0       |              |                   | 2023-05-13T05:24:48.779707Z |
|               |                                          |             | raw_aircraft_data  |          |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v1            | aircraft.etl_flow.extract_live_data      | python-task |                    | o0       |              |                   | 2023-05-13T05:24:48.771175Z |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
| v1            | aircraft.etl_flow.extract_reference_data | python-task |                    | airlines |              |                   | 2023-05-13T05:24:48.756913Z |
|               |                                          |             |                    | airports |              |                   |                             |
|               |                                          |             |                    | routes   |              |                   |                             |
 --------------- ------------------------------------------ ------------- -------------------- ---------- -------------- ------------------- ----------------------------- 
15 rows
```

### Provide a possible output or UX example

`flytectl get task --version v3` filters to just tasks at version `v3`.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment] 2023-05-30 22:18
@tekumara , this is a dupe of https://github.com/flyteorg/flyte/issues/3301#issuecomment-1412259089.

Please, reopen if you need any clarification.

**Closed by eapolinario** 2023-05-30 22:18 UTC
Labels: enhancement, untriaged
