### ISSUE TITLE
[BUG] UI adds spaces to strings inside structs

### ISSUE THREAD

**Issue by ggydush** [flyteorg/flyte#4052] opened 2023-09-19 23:26 UTC
### Describe the bug

When using both dict and dataclass types, the types are represented as a struct in the FlyteConsole. If the struct has a string with commas in it, a space character is added after every comma in the FlyteConsole's Input fields box when launching a workflow (example: "a,b,c" turns into "a, b, c, "). Clicking "Relaunch" adds an additional space as well ("a, b, c, " turns into "a,  b,  c,  ").

### Expected behavior

Strings with commas have no added spaces in the FlyteConsole when used within struct types.

### Additional context to reproduce

```python

from dataclasses_json import DataClassJsonMixin
from flytekit import task, workflow


@dataclass
class TestClass(DataClassJsonMixin):
    a: str = "this,causes,issues"


@task
def test_task(spec: TestClass) -> None:
    return


@workflow
def test_workflow(spec: TestClass = TestClass()) -> None:
    return test_task(spec=spec)
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by shraddhadev24** [comment] 2023-09-30 04:11
can you please assign this issue to me

**Comment by lazyMonk1010** [comment] 2023-10-06 18:33
hey @ggydush @samhita-alla  i want to work on this issue , can you please assign me this!

**Comment by samhita-alla** [comment] 2023-10-09 09:48
@shraddhadev24, are you working on this issue?

**Comment by shraddhadev24** [comment] 2023-10-10 01:48
@samhita-alla  I need time around. You can assign to @lazyMonk1010

**Comment by vaibhav-1508** [comment] 2023-10-13 08:47
Hey there! Are you still working on this issue @lazyMonk1010 ?
If not, can I be assigned to this issue. Thank you!!🚀

**Comment by mecskyverse** [comment] 2023-10-19 08:49
Hey, @vaibhav-1508 , are you currently working on this issue? It's been a long time since your last follow-up.

**Comment by samhita-alla** [comment] 2023-10-24 09:30
@mecskyverse, please feel free to create a PR.

**Comment by aashish-g03** [comment] 2024-10-05 23:07
Hi @samhita-alla , 
I noticed that the issue isn't marked as high priority. If it's not an urgent requirement, could you please assign it to me? 
I'm still familiarizing myself with open source contributions and would love to take this on. In case I encounter any difficulties, I’ll be sure to let you know so we can reassign if needed.

**Comment by samhita-alla** [comment] 2024-10-07 09:09
@aashish-g03 It looks like this issue has already been fixed, sorry about that! Here are the issues that still don't have an assignee: https://github.com/flyteorg/flyte/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest+no%3Aassignee. If you'd like to contribute to any of these, let us know!

**Closed by samhita-alla** 2024-10-07 09:09 UTC
Labels: bug, hacktoberfest

**Comment by aashish-g03** [comment] 2024-10-07 15:49
No problem, @samhita-alla. Could you please assign this issue to me: https://github.com/flyteorg/flyte/issues/5534?

It seems like another beginner-friendly issue I can work on to further familiarize myself with open source contributions.
