### ISSUE TITLE
[K8s-Array ] Retries in array tasks retry the entire array task instead of the subtasks

### ISSUE THREAD

**Issue by migueltol22** [flyteorg/flyte#190] opened 2020-03-04 17:25 UTC
Currently, when a dynamic task spawns N number of subtasks, if any of these subtasks fail, flyte will retry the parent task instead of the single subtask even if retries are set at the subtask level.

**Comment by EngHabu** [comment] 2020-03-04 17:56
K8s-Array plugin executes arrays by creates N Pods (where N is the total number of subtasks requested). Pods currently do not support a max_retry count (there is an issue and a [PR](https://github.com/kubernetes/kubernetes/pull/79334) to add that). On the contrary, AWS_Array plugin can pass the max retries requested to AWS batch service. I agree the difference in behavior is not desirable. 

Until the above PR is merged (to match AWS Batch behavior), we can implement the retry logic within the plugin as follows:

1. [This](https://github.com/lyft/flyteplugins/blob/master/go/tasks/plugins/array/k8s/executor.go#L79-L84) is the relevant part of State Machine of the K8s-Array plugin.

2. [This](https://github.com/lyft/flyteplugins/blob/master/go/tasks/plugins/array/k8s/monitor.go#L62-L66) is where it checks the pod status and where it should determine whether it can retry or not based on the task [template metadata](https://github.com/lyft/flyteidl/blob/master/protos/flyteidl/core/tasks.proto#L73).

3. We will need to update the [generated pod name](https://github.com/lyft/flyteplugins/blob/master/go/tasks/plugins/array/k8s/launcher.go#L82) to include the retry index. (Tip: to keep backward compat, for retry 0, don't change the name)
Pod names should always be deterministic to avoid any two phase commit issues (if we launch the 2nd attempt but fail to persist to etcd. the new state, when we come back to retry the same operation, we will attempt to launch the 2nd attempt again only to discover the pod exists... should not be treated as an error case)

4. We will need to persist the current retry attempt index in the [state](https://github.com/lyft/flyteplugins/blob/master/go/tasks/plugins/array/k8s/executor.go#L59) as well to ensure we do not exceed the allowed retry count.

Please let me know if you have questions about the approach or suggestions to simplify it...

**Comment by kumare3** [comment] 2021-02-09 00:07
@migueltol22 are you working on this or is this done? Can we close it out?

**Comment by katrogan** [comment] 2021-08-11 20:23
duplicate of https://github.com/flyteorg/flyte/issues/1276

**Closed by katrogan** 2021-08-11 20:23 UTC
Labels: enhancement
