### ISSUE TITLE
[BUG] unable to start flyte in Docker windows

### ISSUE THREAD

**Issue by arcangelsalazar** [flyteorg/flyte#1321] opened 2021-08-09 01:28 UTC
Just trying to execute 

`docker run --rm --privileged -p 30081:30081 -p 30084:30084 cr.flyte.org/flyteorg/flyte-sandbox`

in windows 10 pro with hyper-v docker desktop gives the output:

```
Starting k3s cluster...
Done.
Deploying Flyte...
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/flyteorg/share'
```

```
docker -v
Docker version 20.10.7, build f0df350
```

```
image-id
938b32974014
```

**Comment by kumare3** [comment] 2021-08-09 02:49
This should have worked - cc @evalsocket

**Comment by evalsocket** [comment] 2021-08-09 16:46
@arcangelsalazar i found the issue and issue exist in non dind image. This will work in dind image 
```bash
$ docker run --rm --privileged -p 30081:30081 -p 30084:30084 cr.flyte.org/flyteorg/flyte-sandbox:dind
```

I will create a hotfix today

**Comment by SteVwonder** [comment] 2021-08-24 04:33
Just wanted to note that I am running into the issue with the `latest` tag even after #1322 was merged. It does work with the `dind` tag though.  Maybe a deploy of `latest` failed?  Or there was a regression?  Or maybe this is expected because the `latest` tag is only updated with a new tagged version? (I'll admit to being unfamiliar with your deploy process).

```
→   docker run --rm --privileged -p 30081:30081 -p 30084:30084 cr.flyte.org/flyteorg/flyte-sandbox

Unable to find image 'cr.flyte.org/flyteorg/flyte-sandbox:latest' locally
latest: Pulling from flyteorg/flyte-sandbox
540db60ca938: Pull complete 
9f556c01e7fe: Pull complete 
90bf6cdf185f: Pull complete 
33f48319242b: Pull complete 
7afb9667908f: Pull complete 
90d268df81d4: Pull complete 
c40382cac44f: Pull complete 
6142673bce79: Pull complete 
88d01f953349: Pull complete 
13216d8ad077: Pull complete 
Digest: sha256:e9170923c33236bbca5d1beb6abcf1809f65c6a2c6a390f0069717f7fc36d5f6
Status: Downloaded newer image for cr.flyte.org/flyteorg/flyte-sandbox:latest
Starting k3s cluster...
Done.
Deploying Flyte...
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/flyteorg/share'

→ docker run --rm --privileged -p 30081:30081 -p 30084:30084 cr.flyte.org/flyteorg/flyte-sandbox:dind
Unable to find image 'cr.flyte.org/flyteorg/flyte-sandbox:dind' locally
dind: Pulling from flyteorg/flyte-sandbox
540db60ca938: Already exists 
5a38b3726f4b: Pull complete 
e5fa5deb3340: Pull complete 
c521bbbd9945: Pull complete 
59707d521c45: Pull complete 
26abe223b186: Pull complete 
9d806bc20361: Pull complete 
918595a0e69b: Pull complete 
eaf6f33d26f8: Pull complete 
3b0522a0264f: Pull complete 
7f8d570be227: Pull complete 
11903f101372: Pull complete 
00e9c81be790: Pull complete 
f81804ea7971: Pull complete 
487526c3876b: Pull complete 
Digest: sha256:1fbc95a1ae1c7fd65945021ca6126c4a0c19ed98528ea623922100017391238a
Status: Downloaded newer image for cr.flyte.org/flyteorg/flyte-sandbox:dind
Starting Docker daemon...
Done.
Starting k3s cluster...
Done.
Deploying Flyte...
namespace/flyte created
namespace/kubernetes-dashboard created
namespace/projectcontour created
<snip>
ingress.networking.k8s.io/flytesystem created
ingress.networking.k8s.io/minio created
Waiting for Flyte to become ready...
```

**Comment by kumare3** [comment] 2021-08-24 07:18
@SteVwonder thank you for the issue report. Cc @evalsocket

**Comment by evalsocket** [comment] 2021-08-24 08:28
@SteVwonder The issue is fixed in the master branch. It is not working because we only build sandbox images on release time.

**Closed** 2021-08-30 15:39 UTC
Labels: bug

**Comment by SteVwonder** [comment] 2021-09-01 01:23
> Pushed a prerelease to refresh these images. Mind retrying? 

Confirmed it works.  Thanks!
