### ISSUE TITLE
[BUG] UI shows pod running when waiting.

### ISSUE THREAD

**Issue by ajsalow** [flyteorg/flyte#954] opened 2021-04-29 14:37 UTC
**Describe the bug**
UI shows pod running when it is actually waiting.
<img width="1647" alt="Screen Shot 2021-04-29 at 9 22 48 AM" src="https://user-images.githubusercontent.com/12450632/116568698-4dfba980-a8ce-11eb-8d99-c66c2fff7e81.png">

**Expected behavior**
"Running", to me, means the pod is executing the task. If it is waiting, it should not say running.

**Comment by EngHabu** [comment] 2021-08-31 00:40
dupe of https://github.com/flyteorg/flyte/issues/1392

**Closed by EngHabu** 2021-08-31 00:40 UTC
Labels: bug, untriaged
