### ISSUE TITLE
[Core feature] Support overriding node name

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3092] opened 2022-11-21 20:34 UTC
### Motivation: Why do you think this is important?

When composing a workflow out of tasks, it is not always good enough to use the task name as is (Python function name) for node name, and sometimes it is better give a more meaningful node name. This is currently not supported by flytekit.

### Goal: What should the final outcome look like, ideally?

Users can override node name using `with_overrides(name="A better Task Name")` in flytekit.

### Describe alternatives you've considered 

There is no alternative can achieve this.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by honnix** [comment] 2022-11-28 12:56
Note that this issue is not fully addressed because of https://github.com/flyteorg/flyte/issues/3092

**Comment by jsonporter** [comment] 2023-03-16 22:38
Closing as dupe of #3470

**Closed by jsonporter** 2023-03-16 22:38 UTC
Labels: enhancement, untriaged
