### ISSUE TITLE
[BUG] workflow without execution cannot be failed/aborted/finalized correctly after max retry

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#2577] opened 2022-06-03 09:42 UTC
### Describe the bug

For unknown reason, we have a workflow execution that never managed to start with error:
```
ExecutionNotFound: The execution that the event belongs to does not exist,
    caused by [rpc error: code = NotFound desc = missing entity of type execution
    with identifier project...
```

So trying to mutate this workflow will always result in failure and eventually `mutableW.Status.FailedAttempts > maxRetries`.

When this happens, the abort process cannot handle it correctly.

If we try to trace back the very first time when retry was exhausted, there was an error when publishing event because for same reason that the execution did not exist. However, transitioning to `StatusFailed` would fail because of failing to publish event and that did not match [this condition](https://github.com/flyteorg/flytepropeller/blob/c016dabbfef6037bead59590b42326dabe89f957/pkg/controller/workflow/executor.go#L345); and then everything would be retried over and over again as we have seen logs like `RuntimeExecutionError: max number of system retry attempts [38676/50] exhausted`. [These lines](https://github.com/flyteorg/flytepropeller/blob/c016dabbfef6037bead59590b42326dabe89f957/pkg/controller/handler.go#L255-L270) also seems to be related.

And this of course prevents GC from cleaning it up.

### Expected behavior

Workflow can be terminated successfully even it didn't start.

### Additional context to reproduce

Not sure the root cause of missing execution, so don't know how to reproduce it.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by hamersaw** [comment] 2022-06-06 07:59
@honnix is this a duplicate of https://github.com/flyteorg/flyte/issues/2275? Can we close this one?

**Closed** 2022-06-06 08:09 UTC
Labels: bug
