### ISSUE TITLE
[BUG] Large error messages exceed grpc metadata size limit

### ISSUE THREAD

**Issue by neilisaur** [flyteorg/flyte#5224] opened 2024-04-11 16:39 UTC
### Describe the bug

When an error message is being returned to the client in which the error message + other metadata is greater than the grpc.grpc_metadata_size default limit of 16384 bytes, the caller receives an error message like: 

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "received metadata size exceeds hard limit (17137 vs. 16384);  :status:42B content-type:60B grpc-status:44B grpc-message:16991B"
        debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-11T12:20:46.146325605+00:00", grpc_status:8, grpc_message:"received metadata size exceeds hard limit (17137 vs. 
16384);  :status:42B content-type:60B grpc-status:44B grpc-message:16991B"}"
```

### Expected behavior

Return a truncated error message instead of possibly incurring a gRPC error that means little to the caller.

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by neilisaur** [comment] 2024-04-11 16:41
Ref:
https://grpc.github.io/grpc/core/group__grpc__arg__keys.html#ga2a9e23d3fe81ae539ba655d2e49051c8
https://grpc.io/docs/guides/metadata/

**Comment by wild-endeavor** [comment] 2024-04-15 21:37
hey @neilisaur could you give us a bit more context here please?  where are you seeing this?  from which service to which service?  Is this while trying to upload an error.pb file?

thank you for the report.

**Comment by neilisaur** [comment] 2024-04-15 22:39
Sure! The ultimate problem was the error message received when submitting a `pyflyte run` that had a very large data structure within the functions that were specified as @tasks.

The data object itself had a missing field, so flyteadmin tried to return the structure itself and that it was missing a field "xxxx", but that error message that included the data structure itself was too large for the grpc metadata to return, thus the grpc status code of RESOURCE_EXHAUSTED against the grpc metadata's builtin size max size of 16384 bytes.

Here's an example of the error message it was trying to dump into the grpc metadata message:

```
{"json":{"src":"workflow_manager.go:148","wf":"train.train_wf","x-request-id":"xxxxxxx"},"level":"error","msg":"Failed to compile workflow with err: failed to compile workflow with err Collected Errors: 1\n\tError 0: Code: FieldNotFound, Node Id: n2, Description: Variable [hp] (type [simple:STRUCT  metadata:{fields:{<soooomuchdatahere, like 15KB>}]) doesn't have field [exp_hp].\n","ts":"2024-04-11T12:20:46Z"}
```

**Comment by wild-endeavor** [comment] 2024-04-17 00:58
Will continue looking into this.  I'm able to repro this issue locally, but I'm not sure where the issue is coming from.  I feel like it might be a client side problem rather than server side.

**Comment by wild-endeavor** [comment] 2024-04-17 18:24
yeah this is purely a client side thing.  on the server side, admin already has a setting [to gate it](https://github.com/flyteorg/flyte/blob/1757750e580a0ff03fec877ba792a69825a3b720/flyteadmin/pkg/rpc/adminservice/util/transformers.go#L12).

If you do this, it works, https://github.com/flyteorg/flytekit/pull/2359.  Feel free to pull that branch and `export PYTHONPATH` to point to it you should see it pass.

Not sure what to do about this though.  In order to get this in we need to think about the proper ux to expose these configuration knobs to the user.

**Comment by neilisaur** [comment] 2024-04-17 22:51
I think it may be better targeted from the other side; is the underlying error message generation (in this case the data object structure being invalid) that I’m seeing also happening on the client side?

 If so we could cap that with notification of truncation due to metadata max size so that the client gets at least some proper reporting of the underlying error.

Otherwise if we instead wanted to allow larger errors like this wholesale, an addition to the config in a grpc section (without being included in a generated config) could be a quick resolution.
________________________________
From: Yee Hing Tong ***@***.***>
Sent: Wednesday, April 17, 2024 12:24:27 PM
To: flyteorg/flyte ***@***.***>
Cc: Stout, Neil J (US) ***@***.***>; Mention ***@***.***>
Subject: EXTERNAL: Re: [flyteorg/flyte] [BUG] Large error messages exceed grpc metadata size limit (Issue #5224)


yeah this is purely a client side thing. on the server side, admin already has a setting to gate it<https://github.com/flyteorg/flyte/blob/1757750e580a0ff03fec877ba792a69825a3b720/flyteadmin/pkg/rpc/adminservice/util/transformers.go#L12>.

If you do this, it works, flyteorg/flytekit#2359<https://github.com/flyteorg/flytekit/pull/2359>. Feel free to pull that branch and export PYTHONPATH to point to it you should see it pass.

Not sure what to do about this though. In order to get this in we need to think about the proper ux to expose these configuration knobs to the user. Any suggestions @neilisaur<https://github.com/neilisaur> ?

**Comment by wild-endeavor** [comment] 2024-04-18 19:59
I think in general this is an issue that should be fixed.  What I mean is that there is always going to be a class of errors that for whatever reason can only be generated/known from the server side, so we should support it.

@eapolinario I'm wondering if we should just add this option on the flytekit side.  Short of introducing a whole grpc config framework, we can probably just get away with setting this option in flytekit to match the [value in flyte](https://github.com/flyteorg/flyte/blob/0095165f6e910ba911eb157a31e5c6233d5ec2db/flyteadmin/pkg/common/constants.go#L14)?

**Closed** 2024-04-19 20:36 UTC
Labels: bug, flyte-community
