### ISSUE TITLE
[Docs] Some broken link issues and general feedback on new flytecookbooks

### ISSUE THREAD

**Issue by pmahindrakar-oss** [flyteorg/flyte#752] opened 2021-02-20 16:52 UTC
**Describe the documentation update**

- https://docs.flyte.org/en/latest/tutorials/first_example.html
  Contains a tip section but it doesnt provide context of where the args keyword is coming from
- https://flytecookbook.readthedocs.io/en/latest/
   platform documentation link is broken
- https://flytecookbook.readthedocs.io/en/latest/
   ` PR against this or any Flyte repo` Flytesnacks github link would be useful 
- https://flytecookbook.readthedocs.io/en/latest/
  Getting Started appears half way through the page . Should this moved to fresh page?
- https://flytecookbook.readthedocs.io/en/latest/tutorial.html
   Broken link Ensure that you have completed the Getting Started guide.
-  https://flytecookbook.readthedocs.io/en/latest/tutorial.html
    for steps 3 ,4, 5 would be easier to have copy/pastable instructions.
-  https://flytecookbook.readthedocs.io/en/latest/tutorial.html
``It should output `hello world, adam`.``
move the python and it should output outside the box
- https://flytecookbook.readthedocs.io/en/latest/core.html
   `Please see additional information in the GitHub Readme as well.`
     The gihub readme just has one link to the same cookbooks
- https://flytecookbook.readthedocs.io/en/latest/core.html

Some comments over launching the data type example  would be useful 

```
flyte-cli -h localhost:30081 -i list-launch-plan-versions -p flytesnacks -d development | grep PrimitiveDemoWorkflow
flyte-cli -h localhost:30081 -i execute-launch-plan -p flytesnacks -d development -u <urn> -r user -- x=10 y=10.0 s="Hello" b=True
```

-  https://flytecookbook.readthedocs.io/en/latest/core.html
URN => Some explanation of this term could be useful along with usage in flytekit

-  https://flytecookbook.readthedocs.io/en/latest/auto_core_remote_flyte/index.html
   Installing Flyte  is broken

-  flytekit link broken 
https://flytecookbook.readthedocs.io/en/latest/

- https://flytecookbook.readthedocs.io/en/latest/auto_core_remote_flyte/index.html

`1. Run make serialize. This will build the image tagged with just flytecookbook:<sha>, no registry will be prefixed. See the image building section below for additional information.`

Some places we have used fast_serialize .(https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/index.html?highlight=fast_serialize#fast-er-iteration) 
And also from which folder the user has to run it would be useful 

￼

**Comment by kumare3** [comment] 2021-02-20 16:59
@EngHabu fyi

**Comment by evalsocket** [comment] 2021-02-21 22:43
1. As  pmahindrakar mention that in flytekit, we didn't mention the directory. 
2. broken -  https://flytekit.readthedocs.io/en/latest/%22 ( https://docs.flyte.org/projects/cookbook/en/latest/ side menu flytekit python <a>)
3. I didn't find the documentation for sandbox.config

**Comment by samhita-alla** [comment] 2021-02-22 10:30
- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/index.html - Accompanying every step, it'd be useful if we explain the reason behind doing so. For example, in the first step, there's building Dockerfile. Here, if we tell the user about how that has to be done, it'd be great. (We might need to at least point to an example Dockerfile that has already been built for the same purpose).
- The lesser the commands that the user has to run, the more user-friendly the tool/application would be. In the link - https://docs.flyte.org/projects/cookbook/en/latest/auto_core_remote_flyte/index.html, if there's a possibility to reduce the load of commands that the user has to run to leverage the Flyte backend, it'd be great.
- https://docs.flyte.org/projects/cookbook/en/latest/core.html - This link can be included while explaining about how Flyte works. It needn't be there in the cookbook while explaining the examples employing Flyte.
- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/index.html - Rather than including task and workflow in the basic examples section, we can move it on to the top level where we talk about Flyte. Flyte in general has tasks and workflows. So it's better if we introduce these terms in the introductory part itself.
- https://docs.flyte.org/projects/cookbook/en/latest/auto_core_basic/hello_world.html#sphx-glr-auto-core-basic-hello-world-py - This is a duplicate of the first 'Hello World' example. 
- https://docs.flyte.org/projects/cookbook/en/latest/core.html - We can depict more examples explaining how datatype conversions happen for the ones not mentioned in the table. Say, we can pick official examples from TensorFlow and PyTorch to explain how Flyte embeds with the usual DL frameworks. Also for instance, how will we pass Numpy arrays from one task to the other? -  as this isn't a datatype for which the automatic conversion happens. It could be just utilizing the ones already mentioned, but the user might not be knowing about it. In general, it'd be better if we show examples that do not employ many direct data type conversions (from Python to Flyte) as such.

**Comment by kumare3** [comment] 2021-02-23 21:34
@pmahindrakar-oss thank you for the issue. we have tried to address most of the raised concerns.
@samhita-alla I will take   your comment and open a separate issue, this is a great suggestion, but will need a lot more work in the getting started guide and probably better handled as a separate stream

**Comment by kumare3** [comment] 2021-02-28 05:01
Closing this issue, as most of the other requested changes have been made. Thank you folks and if you can give it a go again would be awesome!

**Closed by kumare3** 2021-02-28 05:01 UTC
Labels: bug
