### ISSUE TITLE
[BUG] `launch()` method on launch plans raises exception due to null reference

### ISSUE THREAD

**Issue by matthewphsmith** [flyteorg/flyte#716] opened 2021-02-09 10:43 UTC
**Describe the bug**
Code similar to this:

```
execution = some_launch_plan.launch(
            'project',
            'production',
            name=name,
            inputs={
                'triggered_date': start_date,
            }
        )
execution.wait_for_completion()
if execution.error is not None:
    raise Exception(execution.error)
```

Fails on `launch()` with:

```
  File "/srv/service/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py", line 152, in system_entry_point
    _reraise(ex.type, ex.value, ex.traceback)
  File "/srv/service/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/srv/service/venv/lib/python3.6/site-packages/flytekit/common/exceptions/scopes.py", line 155, in system_entry_point
    return wrapped(*args, **kwargs)
  File "/srv/service/venv/lib/python3.6/site-packages/flytekit/common/launch_plan.py", line 323, in launch_with_literals
    literal_inputs,
  File "/srv/service/venv/lib/python3.6/site-packages/flytekit/clients/friendly.py", line 537, in create_execution
    spec=execution_spec.to_flyte_idl(),
  File "/srv/service/venv/lib/python3.6/site-packages/flytekit/models/execution.py", line 152, in to_flyte_idl
    launch_plan=self.launch_plan.to_flyte_idl(),
AttributeError: 'NoneType' object has no attribute 'to_flyte_idl'
```

**Expected behavior**
Workflow execution starts and a handle object is returned.

**Flyte component**
- [ ] Overall
- [ ] Flyte Setup and Installation scripts
- [ ] Flyte Documentation
- [ ] Flyte communication (slack/email etc)
- [ ] FlytePropeller
- [ ] FlyteIDL (Flyte specification language)
- [ x ] Flytekit (Python SDK)
- [ ] FlyteAdmin (Control Plane service)
- [ ] FlytePlugins
- [ ] DataCatalog 
- [ ] FlyteStdlib (common libraries)
- [ ] FlyteConsole (UI)
- [ ] Other

**To Reproduce**
1. Write a script to import or fetch a launch plan
2. Call launch
3. Appears in version 0.15.4 and 0.14.0

**Comment by kumare3** [comment] 2021-02-09 15:55
This looks like a bad regression? @wild-endeavor

**Comment by wild-endeavor** [comment] 2021-02-10 17:07
I think this is a bad error message, and maybe a bug somewhere else.  `some_launch_plan.id` is missing/None. I'll start a PR to clean up the error message at least, and fix whatever else we find.

**Comment by matthewphsmith** [comment] 2021-02-10 22:31
I was able to work around by using `SdkLaunchPlan.fetch(...)` instead of importing the launch plan directly from code. So I think your diagnosis around the ID being unset is correct.

**Comment by kumare3** [comment] 2021-05-05 22:49
Closing this in favor of the new control plane entities

**Closed by kumare3** 2021-05-05 22:49 UTC
Labels: bug
