### ISSUE TITLE
[Plugin] Keras types integration

### ISSUE THREAD

**Issue by cosmicBboy** [flyteorg/flyte#2759] opened 2022-08-11 12:56 UTC
Flyte is an ML- and data- aware orchestrator, it would make sense to support the most popular ML frameworks as first-class citizen types in the Flyte type system.

One of the popular deep learning frameworks is [keras](https://keras.io/api/), which would make sense to support without installing plugins and simply be activated when a user has it installed, similar to how we're handling [pytorch](https://github.com/flyteorg/flytekit/tree/master/flytekit/extras/pytorch), tensorflow (#2569, #2570, #2571), and sklearn (#2752).

We'll need to follow the conventions set in the [`flytekit.extras.pytorch`](https://github.com/flyteorg/flytekit/tree/master/flytekit/extras/pytorch) module, by doing the following:

1. the `__init__.py` file should handle the case where the user doesn't have `keras` installed.
2. implement a `TypeTransformer` for the following classes:
   - `Model`: https://keras.io/api/models/model/
   - `Sequential`: https://keras.io/api/models/sequential/
   - (TODO: See if there's a single parent class for all keras models 🤷‍♂️)
4. add tests here: https://github.com/flyteorg/flytekit/tree/master/tests/flytekit/unit/extras

#### Resources

- flyte docs: https://docs.flyte.org/projects/cookbook/en/latest/auto/core/extend_flyte/custom_types.html
- saving/loading keras models: https://keras.io/api/models/model_saving_apis/

**Comment by ryankarlos** [comment] 2022-10-18 21:33
Ill pick this up

**Comment by ryankarlos** [comment] 2022-10-19 10:19
take

**Comment by ryankarlos** [comment] 2022-10-19 10:22
#take

**Comment by dennisobrien** [comment] 2022-10-21 05:41
There is another issue that is probably a duplicate of this.  https://github.com/flyteorg/flyte/issues/2570
And that issue also has a PR in progress. https://github.com/flyteorg/flytekit/pull/1241

**Comment by samhita-alla** [comment] 2022-10-24 09:26
@dennisobrien, you're right. @cosmicBboy, which PR shall we close?

**Comment by ryankarlos** [comment] 2022-10-24 10:30
@samhita-alla  Ive also added support for Sequential class in this PR - i could port that over once PR for https://github.com/flyteorg/flyte/issues/2570 is merged in.
Not sure if support for type transformer for https://keras.io/api/layers/ would be useful as well.

**Closed** 2022-10-31 08:57 UTC
Labels: good first issue, plugins, hacktoberfest
