### ISSUE TITLE
[BUG] For incorrect name formats return a better error

### ISSUE THREAD

**Issue by kumare3** [flyteorg/flyte#4174] opened 2023-10-05 06:28 UTC
### Describe the bug

`pyflyte run --remote --name 078b0145-016a-44d8-bac0-fffa2e722f9c test2.py wf --n 10`

returns
```
RPC Failed, with Status: StatusCode.INVALID_ARGUMENT
	details: invalid name format: 078b0145-016a-44d8-bac0-fffa2e722f9c
	Debug string UNKNOWN:Error received from peer ipv4:18.116.105.151:443 {grpc_message:"invalid name format: 078b0145-016a-44d8-bac0-fffa2e722f9c", grpc_status:3, created_time:"2023-10-04T23:18:28.696363-07:00"}
```

This is hard to understand the problem.

The reason is
https://github.com/flyteorg/flyte/blob/81b94a43359adb2d1055e75221048de766769174/flyteadmin/pkg/manager/impl/validation/execution_validator.go#L134
returns just the failing field, it should return the expected regex

### Expected behavior

`invalid name format: 078b0145-016a-44d8-bac0-fffa2e722f9c, does not match regex '^[a-z][a-z\-0-9]*$'`

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by shakeel-3** [comment] 2023-10-05 09:31
Hi @samhita-alla 

I hope you're doing well! I came across this issue and I'm excited about the opportunity to contribute to Hacktoberfest. It looks like a great fit for my skills and interests.

I would love to work on this issue and make a meaningful contribution to the project. Could you please assign it to me, or provide guidance on how I can get started? I'm eager to collaborate with the team and ensure the issue is resolved effectively.

Thank you for your time, and I'm looking forward to being part of this project!

Best regards,
Mohd Shakeel

**Comment by shakeel-3** [comment] 2023-10-05 10:37
@samhita-alla 
Thank you for letting me know! I appreciate your prompt response. It's great to see that the issue has already been addressed with a pull request. 

I'm glad to see the project is so active, and I'll keep an eye out for other opportunities to contribute. If there's anything specific that needs attention or any other way I can help, please feel free to let me know. I'm eager to get involved and contribute to this project.

Thanks again, and happy coding!

Best regards,
Mohd Shakeel

**Comment by iamakhileshmishra** [comment] 2023-10-06 14:18
if this issue is still open i would like to contribute into this please assign this to me.

**Closed** 2023-10-12 06:59 UTC
Labels: bug, hacktoberfest
